name: Deploy to EC2
on:
  push:
    branches:
      - master  # adjust this to your main branch if it's named differently

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # adjust this to your project's node version
    
    - name: Install dependencies and build
      run: |
        npm i pnpm -g
        pnpm i
        npm run build

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ec2-18-234-73-46.compute-1.amazonaws.com
        username: ec2-user
        key: ${{ secrets.AMAZON_SECRET_KEY }}
        source: '.next,package.json,public,Dockerfile,tsconfig.json' # 需要上传的文件
        target: '/home/ec2-user/app/ssr'

    - name: shell EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-18-234-73-46.compute-1.amazonaws.com
        username: ec2-user
        key: ${{ secrets.AMAZON_SECRET_KEY }}
        script: |
          docker images
