name: Deploy to EC2
on:
  push:
    branches:
      - master  # adjust this to your main branch if it's named differently

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # adjust this to your project's node version
    
    - name: Install dependencies and build
      run: |
        npm i pnpm -g
        pnpm i
        npm run build

    - name: Prepare files
      run: |
        mkdir temp
        cp -r .next temp/
        cp -r public temp/
        cp -r package.json temp/
        cp -r Dockerfile temp/
        
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AMAZON_USER_NAME }}
    #     aws-secret-access-key: ${{ secrets.AMAZON_SECRECT_KEY }}
    #     aws-region: ${{ env.AWS_REGION }}

    - name: Copy files to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-34-227-84-173.compute-1.amazonaws.com
        username: ec2-user
        key: ${{ secrets.AMAZON_SECRET_KEY }}
        script: |
          rsync -av --delete $GITHUB_WORKSPACE/temp/* ec2-user@ec2-34-227-84-173.compute-1.amazonaws.com:/home/ec2-user/app/ssr

